name: run-parse-offers-test

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: pull unrelated histories
        run: |
          git pull --allow-unrelated-histories

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.2'
          
      - name: install python packages
        run: |
          export GH_TOKEN = ${{ secrets.GITHUB_TOKEN }}
          python -m pip install --upgrade pip
          pip install -r parse_offers/requirements.txt
          
      - name: execute py script
        run: |
          cd parse_offers
          python3 -m xmlrunner discover

      - name: test summary
        uses: test-summary/action@v1
        with:
          paths: "parse_offers/TEST-*.xml"
        if: always()
